//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public int BenefitId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string MemberPrefixCode { get; set; }
        public string CategoryType { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> Max_Adult { get; set; }
        public Nullable<int> MaxChild { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Duration Duration { get; set; }
    }
}
